linkInt: list.o itemInt.o queueArray.o main.o
	gcc list.o itemInt.o queueArray.o main.o -o queue.exe

list.o: 
	gcc -c list.c

itemInt.o:
	gcc -c itemInt.c

queueArray.o:
	gcc -c queueArray.c


main.o:
	gcc -c main.c

c:
	rm -f *.o *.exe

r:
	./queue.exe
